# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/level-oxygen-447714-d3/test.dockerfile
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY