# config.yaml
data:
  processed_path: "data/processed"

train:
  batch_size: 16
  num_workers: 8
  lr: 0.0001
  dropout: 0.5
  epochs: 10
  devices: 1  # Set to -1 for all available GPUs, or a specific number of GPUs
  log_every_n_steps: 10
  gamma: 0.1
  step_size: 5

env:
  WANDB_API_KEY: ${ secrets.WANDB_API_KEY }

evaluate:
  batch_size: 64
  model_checkpoint: "models/testmodel.pth"

