# config.yaml

model:
  name: resnet50
  num_layers: 50
  learning_rate: 0.001

dataset:
  name: Pokemon
  path: data/processed
  batch_size: 64

training:
  epochs: 20
  seed: 42

evaluation:
  model_checkpoint: checkpoints/best_model.pth