# config.yaml

# Parameters and their default values
model:
  name: resnet50
  num_layers: 50
  learning_rate: 0.001

dataset:
  name: CIFAR10
  path: /data/cifar10
  batch_size: 64

training:
  epochs: 20
  seed: 42