# config.yaml

defaults:
  - optimizer: adam
  - trainer: default

# Model-specific configuration
model:
  num_classes: 1000

# Optimizer configuration
optimizer:
  lr: 1e-3

# Trainer configuration
trainer:
  max_epochs: 10
  accelerator: "auto"
  devices: 1  # Use GPU if available, otherwise CPU
  precision: 32  # Precision for training (16 for mixed precision)
  gpus: 1  # If using GPUs, specify the number of GPUs