# config.yaml
data:
  processed_path: "data/processed"

train:
  batch_size: 32
  num_workers: 4
  lr: 0.0001
  epochs: 1
  devices: 1  # Set to -1 for all available GPUs, or a specific number of GPUs
  log_every_n_steps: 10

env:
  WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

evaluate:
  batch_size: 64
  model_checkpoint: "models/testmodel.pth"

model:
  num_classes: 1000
