name: Local Data Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.png'
      - 'scripts/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Process PNG Data
      run: |
        python scripts/process_png_data.py

    - name: Check data statistics
      run: |
        python scripts/dataset_statistics.py
