name: Local Data Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.png'

jobs:
  run_data_checker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Check data statistics
      run: |
        python src/p100/dataset_statistics.py
    - name: Check data statistics & generate report
      run: |
        python src/p100/data_statistics.md
        echo '![](./mnist_images.png "MNIST images")' >> data_statistics.md
        echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
        echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!
